name: Release on tag
on:
  push:
    tags:
      - v*
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build release
        run: |
          VERSION="v$(jq -r '.version' < manifest.json)"
          if [[ "${VERSION}" != "${{ github.ref_name }}" ]]; then echo "Manifest version!=tag mismatch: ${VERSION} != ${{ github.ref_name }}"; exit 1; fi
          PKG="$(basename ${{ github.repository }})-${{ github.ref_name }}.zip"
          zip -r "${PKG}" *.json src/*
          gh release create ${{ github.ref_name }} "./${PKG}" --generate-notes
